sonar.projectKey=AliHJMM_Mercato
sonar.projectName=Mercato
sonar.projectVersion=1.0

# Modules
sonar.modules=user-service,product-service,media-service,api-gateway,eureka-server,order-service

# Module paths
user-service.sonar.projectBaseDir=backend/user-service
product-service.sonar.projectBaseDir=backend/product-service
media-service.sonar.projectBaseDir=backend/media-service
api-gateway.sonar.projectBaseDir=backend/api-gateway
eureka-server.sonar.projectBaseDir=backend/eureka-server
order-service.sonar.projectBaseDir=backend/order-service

# Sources
sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.language=java
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml