server:
  port: 8084

spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/orderdb}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:dGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBrZXkgZm9yIGp3dCB0b2tlbiBzaWduaW5nIQ==}

product-service:
  url: ${PRODUCT_SERVICE_URL:http://product-service}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
